// Code generated by "stringer -type=Gender"; DO NOT EDIT.

package xone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Other-0]
	_ = x[Female-1]
	_ = x[Male-2]
}

const _Gender_name = "OtherFemaleMale"

var _Gender_index = [...]uint8{0, 5, 11, 15}

func (i Gender) String() string {
	if i < 0 || i >= Gender(len(_Gender_index)-1) {
		return "Gender(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gender_name[_Gender_index[i]:_Gender_index[i+1]]
}
